"""add public key-part to api-key

Revision ID: 2fa4bd670169
Revises: 852702e5c89b
Create Date: 2025-03-14 13:26:01.178891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2fa4bd670169'
down_revision = '852702e5c89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('public_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_api_keys_public_key'), 'api_keys', ['public_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_public_key'), table_name='api_keys')
    op.drop_column('api_keys', 'public_key')
    # ### end Alembic commands ###
