"""not unique user_id on api_key

Revision ID: 852702e5c89b
Revises: 9225801aeff2
Create Date: 2025-03-14 13:05:31.667130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '852702e5c89b'
down_revision = '9225801aeff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=True)
    # ### end Alembic commands ###
